// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SustavZaOrganizacijuNogometnihTurnira.Model.Data;

#nullable disable

namespace SustavZaOrganizacijuNogometnihTurnira.Model.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430151118_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("SustavZaOrganizacijuNogometnihTurnira.Model.Ekipa", b =>
                {
                    b.Property<int>("EkipaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojIgraca")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumOsnutka")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kontakt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrenerIme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("EkipaId");

                    b.ToTable("Ekipe");

                    b.HasData(
                        new
                        {
                            EkipaId = 1,
                            BrojIgraca = 3,
                            DatumOsnutka = new DateTime(1903, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grad = "Zagreb",
                            Kontakt = "0123456789",
                            Naziv = "NK Zagreb",
                            TrenerIme = "Ante"
                        },
                        new
                        {
                            EkipaId = 2,
                            BrojIgraca = 3,
                            DatumOsnutka = new DateTime(1912, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grad = "Split",
                            Kontakt = "0987654321",
                            Naziv = "HNK Split",
                            TrenerIme = "Miroslav"
                        },
                        new
                        {
                            EkipaId = 3,
                            BrojIgraca = 3,
                            DatumOsnutka = new DateTime(1946, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grad = "Rijeka",
                            Kontakt = "0112233445",
                            Naziv = "NK Rijeka",
                            TrenerIme = "Zoran"
                        },
                        new
                        {
                            EkipaId = 4,
                            BrojIgraca = 3,
                            DatumOsnutka = new DateTime(1947, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grad = "Osijek",
                            Kontakt = "0223344556",
                            Naziv = "HNK Osijek",
                            TrenerIme = "Dario"
                        });
                });

            modelBuilder.Entity("SustavZaOrganizacijuNogometnihTurnira.Model.Igrac", b =>
                {
                    b.Property<int>("IgracId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojDresa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("EkipaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pozicija")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Visina")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("IgracId");

                    b.HasIndex("EkipaId");

                    b.ToTable("Igraci");

                    b.HasData(
                        new
                        {
                            IgracId = 1,
                            BrojDresa = 10,
                            DatumRodjenja = new DateTime(1985, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Drzava = "Hrvatska",
                            EkipaId = 1,
                            Ime = "Luka",
                            Pozicija = "Vezni",
                            Prezime = "Modric",
                            Visina = 1.72m
                        },
                        new
                        {
                            IgracId = 2,
                            BrojDresa = 7,
                            DatumRodjenja = new DateTime(1988, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Drzava = "Hrvatska",
                            EkipaId = 1,
                            Ime = "Ivan",
                            Pozicija = "Vezni",
                            Prezime = "Rakitic",
                            Visina = 1.84m
                        },
                        new
                        {
                            IgracId = 3,
                            BrojDresa = 6,
                            DatumRodjenja = new DateTime(1989, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Drzava = "Hrvatska",
                            EkipaId = 1,
                            Ime = "Dejan",
                            Pozicija = "Obrana",
                            Prezime = "Lovren",
                            Visina = 1.88m
                        },
                        new
                        {
                            IgracId = 4,
                            BrojDresa = 9,
                            DatumRodjenja = new DateTime(1986, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Drzava = "Hrvatska",
                            EkipaId = 2,
                            Ime = "Mario",
                            Pozicija = "Napad",
                            Prezime = "Mandzukic",
                            Visina = 1.87m
                        },
                        new
                        {
                            IgracId = 5,
                            BrojDresa = 8,
                            DatumRodjenja = new DateTime(1995, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Drzava = "Hrvatska",
                            EkipaId = 2,
                            Ime = "Marko",
                            Pozicija = "Vezni",
                            Prezime = "Pjaca",
                            Visina = 1.80m
                        },
                        new
                        {
                            IgracId = 6,
                            BrojDresa = 5,
                            DatumRodjenja = new DateTime(1990, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Drzava = "Hrvatska",
                            EkipaId = 2,
                            Ime = "Ante",
                            Pozicija = "Obrana",
                            Prezime = "Buducnost",
                            Visina = 1.85m
                        },
                        new
                        {
                            IgracId = 7,
                            BrojDresa = 14,
                            DatumRodjenja = new DateTime(1992, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Drzava = "Hrvatska",
                            EkipaId = 3,
                            Ime = "Filip",
                            Pozicija = "Vezni",
                            Prezime = "Bradaric",
                            Visina = 1.80m
                        },
                        new
                        {
                            IgracId = 8,
                            BrojDresa = 11,
                            DatumRodjenja = new DateTime(1994, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Drzava = "Hrvatska",
                            EkipaId = 3,
                            Ime = "Mateo",
                            Pozicija = "Vezni",
                            Prezime = "Kovacic",
                            Visina = 1.78m
                        },
                        new
                        {
                            IgracId = 9,
                            BrojDresa = 4,
                            DatumRodjenja = new DateTime(1989, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Drzava = "Hrvatska",
                            EkipaId = 3,
                            Ime = "Domagoj",
                            Pozicija = "Obrana",
                            Prezime = "Vida",
                            Visina = 1.85m
                        },
                        new
                        {
                            IgracId = 10,
                            BrojDresa = 9,
                            DatumRodjenja = new DateTime(1996, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Drzava = "Hrvatska",
                            EkipaId = 4,
                            Ime = "Bruno",
                            Pozicija = "Napad",
                            Prezime = "Petkovic",
                            Visina = 1.87m
                        },
                        new
                        {
                            IgracId = 11,
                            BrojDresa = 8,
                            DatumRodjenja = new DateTime(1990, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Drzava = "Hrvatska",
                            EkipaId = 4,
                            Ime = "Ante",
                            Pozicija = "Vezni",
                            Prezime = "Vukusic",
                            Visina = 1.80m
                        },
                        new
                        {
                            IgracId = 12,
                            BrojDresa = 5,
                            DatumRodjenja = new DateTime(1990, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Drzava = "Hrvatska",
                            EkipaId = 4,
                            Ime = "Dino",
                            Pozicija = "Obrana",
                            Prezime = "Peric",
                            Visina = 1.85m
                        });
                });

            modelBuilder.Entity("SustavZaOrganizacijuNogometnihTurnira.Model.PrijavaEkipe", b =>
                {
                    b.Property<int>("PrijavaEkipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("TEXT");

                    b.Property<int>("EkipaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Potvrdjeno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnirId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrijavaEkipeId");

                    b.HasIndex("EkipaId");

                    b.HasIndex("TurnirId");

                    b.ToTable("PrijaveEkipe");

                    b.HasData(
                        new
                        {
                            PrijavaEkipeId = 1,
                            DatumPrijave = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EkipaId = 1,
                            Potvrdjeno = true,
                            TurnirId = 1
                        },
                        new
                        {
                            PrijavaEkipeId = 2,
                            DatumPrijave = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EkipaId = 2,
                            Potvrdjeno = true,
                            TurnirId = 1
                        },
                        new
                        {
                            PrijavaEkipeId = 3,
                            DatumPrijave = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EkipaId = 3,
                            Potvrdjeno = true,
                            TurnirId = 2
                        },
                        new
                        {
                            PrijavaEkipeId = 4,
                            DatumPrijave = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EkipaId = 4,
                            Potvrdjeno = true,
                            TurnirId = 2
                        },
                        new
                        {
                            PrijavaEkipeId = 5,
                            DatumPrijave = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EkipaId = 1,
                            Potvrdjeno = true,
                            TurnirId = 3
                        },
                        new
                        {
                            PrijavaEkipeId = 6,
                            DatumPrijave = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EkipaId = 3,
                            Potvrdjeno = true,
                            TurnirId = 3
                        });
                });

            modelBuilder.Entity("SustavZaOrganizacijuNogometnihTurnira.Model.Stadion", b =>
                {
                    b.Property<int>("StadionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("StadionId");

                    b.ToTable("Stadioni");

                    b.HasData(
                        new
                        {
                            StadionId = 1,
                            Grad = "Zagreb",
                            Kapacitet = 35000,
                            Naziv = "Stadion Maksimir"
                        },
                        new
                        {
                            StadionId = 2,
                            Grad = "Split",
                            Kapacitet = 18000,
                            Naziv = "Stadion Poljud"
                        },
                        new
                        {
                            StadionId = 3,
                            Grad = "Rijeka",
                            Kapacitet = 20000,
                            Naziv = "Gradski stadion"
                        });
                });

            modelBuilder.Entity("SustavZaOrganizacijuNogometnihTurnira.Model.Sudac", b =>
                {
                    b.Property<int>("SudacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Licenca")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("SudacId");

                    b.ToTable("Sudci");

                    b.HasData(
                        new
                        {
                            SudacId = 1,
                            Ime = "Marko",
                            Licenca = "UEFA-A",
                            Prezime = "Horvat"
                        },
                        new
                        {
                            SudacId = 2,
                            Ime = "Ivan",
                            Licenca = "UEFA-B",
                            Prezime = "Milic"
                        },
                        new
                        {
                            SudacId = 3,
                            Ime = "Petar",
                            Licenca = "UEFA-A",
                            Prezime = "Novak"
                        });
                });

            modelBuilder.Entity("SustavZaOrganizacijuNogometnihTurnira.Model.Turnir", b =>
                {
                    b.Property<int>("TurnirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumZavrsetka")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximalanBrojEkipa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("TurnirId");

                    b.ToTable("Turniri");

                    b.HasData(
                        new
                        {
                            TurnirId = 1,
                            DatumPocetka = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumZavrsetka = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaximalanBrojEkipa = 16,
                            Naziv = "Ljetni nogometni turnir",
                            Opis = "Ljetni kup turnir za amaterske ekipe.",
                            Tip = 4
                        },
                        new
                        {
                            TurnirId = 2,
                            DatumPocetka = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumZavrsetka = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaximalanBrojEkipa = 2,
                            Naziv = "Zimski nogometni turnir",
                            Opis = "Zimski liga turnir za amaterske ekipe.",
                            Tip = 3
                        },
                        new
                        {
                            TurnirId = 3,
                            DatumPocetka = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumZavrsetka = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaximalanBrojEkipa = 8,
                            Naziv = "Proljetni nogometni turnir",
                            Opis = "Proljetni kup turnir za amaterske ekipe.",
                            Tip = 1
                        });
                });

            modelBuilder.Entity("SustavZaOrganizacijuNogometnihTurnira.Model.Utakmica", b =>
                {
                    b.Property<int>("UtakmicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumVrijeme")
                        .HasColumnType("TEXT");

                    b.Property<int>("DomacaEkipaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoloviDomace")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoloviGosta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GostujucaEkipaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("StadionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("SudacId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnirId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UtakmicaId");

                    b.HasIndex("DomacaEkipaId");

                    b.HasIndex("GostujucaEkipaId");

                    b.HasIndex("StadionId");

                    b.HasIndex("SudacId");

                    b.HasIndex("TurnirId");

                    b.ToTable("Utakmice");

                    b.HasData(
                        new
                        {
                            UtakmicaId = 1,
                            DatumVrijeme = new DateTime(2024, 7, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DomacaEkipaId = 1,
                            GoloviDomace = 2,
                            GoloviGosta = 1,
                            GostujucaEkipaId = 2,
                            Napomena = "Dobra utakmica, puno navijaca.",
                            StadionId = 1,
                            Status = "Zavrsena",
                            SudacId = 1,
                            TurnirId = 1
                        },
                        new
                        {
                            UtakmicaId = 2,
                            DatumVrijeme = new DateTime(2024, 12, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DomacaEkipaId = 3,
                            GoloviDomace = 1,
                            GoloviGosta = 1,
                            GostujucaEkipaId = 4,
                            Napomena = "Izjednacena utakmica.",
                            StadionId = 2,
                            Status = "Zavrsena",
                            SudacId = 2,
                            TurnirId = 2
                        },
                        new
                        {
                            UtakmicaId = 3,
                            DatumVrijeme = new DateTime(2024, 3, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DomacaEkipaId = 1,
                            GoloviDomace = 0,
                            GoloviGosta = 2,
                            GostujucaEkipaId = 3,
                            Napomena = "Dobra utakmica, ali domacini nisu uspjeli postici gol.",
                            StadionId = 3,
                            Status = "Zavrsena",
                            SudacId = 3,
                            TurnirId = 3
                        });
                });

            modelBuilder.Entity("SustavZaOrganizacijuNogometnihTurnira.Model.Igrac", b =>
                {
                    b.HasOne("SustavZaOrganizacijuNogometnihTurnira.Model.Ekipa", "Ekipa")
                        .WithMany("Igraci")
                        .HasForeignKey("EkipaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekipa");
                });

            modelBuilder.Entity("SustavZaOrganizacijuNogometnihTurnira.Model.PrijavaEkipe", b =>
                {
                    b.HasOne("SustavZaOrganizacijuNogometnihTurnira.Model.Ekipa", "Ekipa")
                        .WithMany("PrijaveEkipe")
                        .HasForeignKey("EkipaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SustavZaOrganizacijuNogometnihTurnira.Model.Turnir", "Turnir")
                        .WithMany("PrijaveEkipe")
                        .HasForeignKey("TurnirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekipa");

                    b.Navigation("Turnir");
                });

            modelBuilder.Entity("SustavZaOrganizacijuNogometnihTurnira.Model.Utakmica", b =>
                {
                    b.HasOne("SustavZaOrganizacijuNogometnihTurnira.Model.Ekipa", "DomacaEkipa")
                        .WithMany("DomaceUtakmice")
                        .HasForeignKey("DomacaEkipaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SustavZaOrganizacijuNogometnihTurnira.Model.Ekipa", "GostujucaEkipa")
                        .WithMany("GostujuceUtakmice")
                        .HasForeignKey("GostujucaEkipaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SustavZaOrganizacijuNogometnihTurnira.Model.Stadion", "Stadion")
                        .WithMany("Utakmice")
                        .HasForeignKey("StadionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SustavZaOrganizacijuNogometnihTurnira.Model.Sudac", "Sudac")
                        .WithMany("Utakmice")
                        .HasForeignKey("SudacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SustavZaOrganizacijuNogometnihTurnira.Model.Turnir", "Turnir")
                        .WithMany("Utakmice")
                        .HasForeignKey("TurnirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DomacaEkipa");

                    b.Navigation("GostujucaEkipa");

                    b.Navigation("Stadion");

                    b.Navigation("Sudac");

                    b.Navigation("Turnir");
                });

            modelBuilder.Entity("SustavZaOrganizacijuNogometnihTurnira.Model.Ekipa", b =>
                {
                    b.Navigation("DomaceUtakmice");

                    b.Navigation("GostujuceUtakmice");

                    b.Navigation("Igraci");

                    b.Navigation("PrijaveEkipe");
                });

            modelBuilder.Entity("SustavZaOrganizacijuNogometnihTurnira.Model.Stadion", b =>
                {
                    b.Navigation("Utakmice");
                });

            modelBuilder.Entity("SustavZaOrganizacijuNogometnihTurnira.Model.Sudac", b =>
                {
                    b.Navigation("Utakmice");
                });

            modelBuilder.Entity("SustavZaOrganizacijuNogometnihTurnira.Model.Turnir", b =>
                {
                    b.Navigation("PrijaveEkipe");

                    b.Navigation("Utakmice");
                });
#pragma warning restore 612, 618
        }
    }
}
